version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 723446198494.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t latti99 .
      - docker tag latti99:latest 723446198494.dkr.ecr.us-east-2.amazonaws.com/latti99:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 723446198494.dkr.ecr.ap-south-1.amazonaws.com/latti99:latest
      - envsubst < "fargate.template.json" > "fargate.json"
artifacts:
  files:
    - 'fargate.json'
  name: $IMAGE_TAG
